"""BlindSpot — Hidden Dependency Discovery (Stages 1-7, hybrid, Report)."""

from .discovery import Candidate, discover_candidates
from .filtering import (
    EvidencePackage,
    build_evidence_package,
    build_evidence_packages,
    filter_and_build_evidence,
    filter_candidates,
    filter_with_reasons,
)
from .judge import (
    DEFAULT_MODEL,
    FAILSAFE_MODEL,
    GEMINI_DEFAULT_MODEL,
    GEMINI_FAILSAFE_MODEL,
    OPENROUTER_BASE_URL,
    OPENROUTER_DEFAULT_MODEL,
    OPENROUTER_MAX_TOKENS,
    THINKING_BUDGETS,
    GeminiJudgeClient,
    JudgeResult,
    OpenRouterJudgeClient,
    build_grouped_judge_prompt,
    build_judge_prompt,
    failsafe_result,
    judge_evidence_package,
    judge_evidence_packages,
    judge_grouped_package,
    judge_grouped_packages,
    placeholder_future_judge,
)
from .graph import (
    GraphData,
    GraphEdge,
    GraphNode,
    build_graph,
    build_graph_data,
    build_graph_data_from_groups,
    build_graph_from_groups,
)
from .model import Dependency, DependencyModel, build_dependency_model
from .coupling import CouplingGroup, CouplingModel, build_coupling_model
from .aggregation import GroupedEvidencePackage, aggregate_evidence_packages
from .context import ContextBundle, build_context_bundle, build_file_tree, collect_source_snippets
from .context_judge import (
    MicroSignal,
    QUESTIONS,
    build_contextual_prompt,
    judge_contextual_package,
    judge_contextual_packages,
    parse_or_failsafe,
    signals_to_judge_result,
    validate_signals,
)
from .scoring import SCORING_VERSION, ScoringResult, score_group
from .report import (
    GroupedReportData,
    GroupedReportFinding,
    ReportData,
    ReportFinding,
    build_grouped_report,
    build_report,
)
from .parser import (
    Project,
    Service,
    Volume,
    load_env_file,
    normalize_environment,
    normalize_volume,
    normalize_volumes,
    parse_compose_file,
    parse_project,
)
from .resolution import (
    ResolutionResult,
    ResolutionStep,
    bounded_resolve,
    build_lookup,
)

__all__ = [
    "Candidate",
    "CouplingGroup",
    "CouplingModel",
    "ContextBundle",
    "MicroSignal",
    "Dependency",
    "DependencyModel",
    "EvidencePackage",
    "GraphData",
    "GraphEdge",
    "GraphNode",
    "GroupedEvidencePackage",
    "GroupedReportData",
    "GroupedReportFinding",
    "JudgeResult",
    "Project",
    "ReportData",
    "ReportFinding",
    "Service",
    "Volume",
    "DEFAULT_MODEL",
    "FAILSAFE_MODEL",
    "GEMINI_DEFAULT_MODEL",
    "GEMINI_FAILSAFE_MODEL",
    "OPENROUTER_BASE_URL",
    "OPENROUTER_DEFAULT_MODEL",
    "OPENROUTER_MAX_TOKENS",
    "THINKING_BUDGETS",
    "GeminiJudgeClient",
    "OpenRouterJudgeClient",
    "aggregate_evidence_packages",
    "build_context_bundle",
    "build_contextual_prompt",
    "build_coupling_model",
    "build_dependency_model",
    "build_evidence_package",
    "build_evidence_packages",
    "build_graph",
    "build_graph_data",
    "build_graph_data_from_groups",
    "build_graph_from_groups",
    "build_grouped_report",
    "build_grouped_judge_prompt",
    "build_judge_prompt",
    "build_report",
    "discover_candidates",
    "failsafe_result",
    "filter_and_build_evidence",
    "filter_candidates",
    "filter_with_reasons",
    "judge_contextual_package",
    "judge_contextual_packages",
    "judge_evidence_package",
    "judge_evidence_packages",
    "judge_grouped_package",
    "judge_grouped_packages",
    "load_env_file",
    "normalize_environment",
    "normalize_volume",
    "normalize_volumes",
    "parse_compose_file",
    "parse_project",
    "parse_or_failsafe",
    "placeholder_future_judge",
    "score_group",
    "signals_to_judge_result",
    "validate_signals",
]
