"""BlindSpot — Hidden Dependency Discovery (Stages 1-5, hybrid)."""

from .discovery import Candidate, discover_candidates
from .filtering import (
    EvidencePackage,
    build_evidence_package,
    build_evidence_packages,
    filter_and_build_evidence,
    filter_candidates,
    filter_with_reasons,
)
from .judge import (
    DEFAULT_MODEL,
    FAILSAFE_MODEL,
    GEMINI_DEFAULT_MODEL,
    GEMINI_FAILSAFE_MODEL,
    OPENROUTER_BASE_URL,
    OPENROUTER_DEFAULT_MODEL,
    OPENROUTER_MAX_TOKENS,
    THINKING_BUDGETS,
    GeminiJudgeClient,
    JudgeResult,
    OpenRouterJudgeClient,
    build_judge_prompt,
    failsafe_result,
    judge_evidence_package,
    judge_evidence_packages,
    placeholder_future_judge,
)
from .model import Dependency, DependencyModel, build_dependency_model
from .parser import (
    Project,
    Service,
    Volume,
    load_env_file,
    normalize_environment,
    normalize_volume,
    normalize_volumes,
    parse_compose_file,
    parse_project,
)

__all__ = [
    "Candidate",
    "Dependency",
    "DependencyModel",
    "EvidencePackage",
    "JudgeResult",
    "Project",
    "Service",
    "Volume",
    "DEFAULT_MODEL",
    "FAILSAFE_MODEL",
    "GEMINI_DEFAULT_MODEL",
    "GEMINI_FAILSAFE_MODEL",
    "OPENROUTER_BASE_URL",
    "OPENROUTER_DEFAULT_MODEL",
    "OPENROUTER_MAX_TOKENS",
    "THINKING_BUDGETS",
    "GeminiJudgeClient",
    "OpenRouterJudgeClient",
    "build_dependency_model",
    "build_evidence_package",
    "build_evidence_packages",
    "build_judge_prompt",
    "discover_candidates",
    "failsafe_result",
    "filter_and_build_evidence",
    "filter_candidates",
    "filter_with_reasons",
    "judge_evidence_package",
    "judge_evidence_packages",
    "load_env_file",
    "normalize_environment",
    "normalize_volume",
    "normalize_volumes",
    "parse_compose_file",
    "parse_project",
    "placeholder_future_judge",
]
